CREATE TABLE Usuarios (
    id_usuario        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(100) NOT NULL,
    apellido          VARCHAR2(100) NOT NULL,
    correo            VARCHAR2(120) UNIQUE NOT NULL
);


CREATE TABLE Estudiantes (
    id_estudiante     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario        NUMBER NOT NULL,
    PrestamosActivos INTEGER NOT NULL,
    Estado VARCHAR2(100) NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)
);


CREATE TABLE Docentes (
    id_docente        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario        NUMBER NOT NULL,
    id_material_exclusivo  INTEGER,
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario),
    FOREIGN KEY (id_material_exclusivo) REFERENCES MaterialExclusivo(id_material_exclusivo)
);


CREATE TABLE Investigadores (
    id_investigador   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario        integer NOT NULL,
    id_Data_Set_Descargado  INTEGER,
    NivelAcceso VARCHAR2(100) NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario),
    FOREIGN KEY (id_Data_Set_Descargado) REFERENCES DataSetsDescargados(id_Data_Set_Descargado)
);


CREATE TABLE Libros (
    id_libro          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_prestamo       integer not null,
    Nombre            VARCHAR2(150) NOT NULL,
    autor             VARCHAR2(150),
    anio_publicacion NUMBER(4),
    CantidadPaginas INTEGER,
    Cantidad INTEGER,
    Descripcion VARCHAR2(100),
    FOREIGN KEY (id_prestamo) REFERENCES Prestamos(id_prestamo)
);


CREATE TABLE Prestamos (
    id_prestamo       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estudiante        NUMBER NOT NULL,
    id_libro          NUMBER NOT NULL,
    cantidad INTEGER NOT NULL,
    fecha_prestamo    DATE DEFAULT SYSDATE,
    fecha_devolucion  DATE,
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario),
    FOREIGN KEY (id_libro) REFERENCES Libros(id_libro)
);


CREATE TABLE DataSetsDescargados(
    id_Data_Set_Descargado  INTEGER PRIMARY KEY,
    id_investigador         INTEGER NOT NULL,
    Nombre                  VARCHAR2(300) NOT NULL,
    Cantidad                INTEGER NOT NULL,
    FOREIGN KEY (id_investigador) REFERENCES Investigadores(id_investigador)
);

CREATE TABLE MaterialExclusivo (
    id_material_exclusivo  INTEGER PRIMARY KEY,
    id_docente             INTEGER NOT NULL,
    nombre                 VARCHAR2(150) NOT NULL,
    descripcion            VARCHAR2(300) NOT NULL,
    FOREIGN KEY (id_docente) REFERENCES Docentes(id_docente)
);


CREATE TABLE Biblioteca(
    id_biblioteca       INTEGER PRIMARY KEY,
    id_usuario         INTEGER NOT NULL,
    CantidadMaterial    INTEGER NOT NULL,
    GestionPrestamo     INTEGER NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)
);

