CREATE TABLE Usuarios (
    id_usuario        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(100) NOT NULL,
    apellido          VARCHAR2(100) NOT NULL,
    correo            VARCHAR2(120) UNIQUE NOT NULL,
    tipo_usuario      VARCHAR2(20) CHECK (tipo_usuario IN ('estudiante','docente','investigador','Biblioteca'))
);


CREATE TABLE Estudiantes (
    id_estudiante     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario        NUMBER NOT NULL,
    PrestamosActivos INTEGER NOT NULL,
    EstadoDeuda VARCHAR2(50) NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)
);


CREATE TABLE Docentes (
    id_docente        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario        NUMBER NOT NULL,
    MaterialExclusivoAccedido VARCHAR2(50) NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)
);


CREATE TABLE Investigadores (
    id_investigador   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario        NUMBER NOT NULL,
    NivelAcceso VARCHAR2(50) NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)
);


CREATE TABLE Libros (
    id_libro          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre            VARCHAR2(150) NOT NULL,
    autor             VARCHAR2(150),
    anio_publicacion NUMBER(4),
    CantidadPaginas INTEGER,
    Cantidad INTEGER,
    Descripcion VARCHAR2(100)
);


CREATE TABLE Prestamos (
    id_prestamo       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estudiante        NUMBER NOT NULL,
    id_libro          NUMBER NOT NULL,
    cantidad INTEGER NOT NULL,
    fecha_prestamo    DATE DEFAULT SYSDATE,
    fecha_devolucion  DATE,
    estado            VARCHAR2(20) CHECK (estado IN ('pendiente','devuelto','retrasado')),
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario),
    FOREIGN KEY (id_libro) REFERENCES Libros(id_libro)
);


CREATE TABLE DataSetsDescargados(
    id_Data_Set_Descargado  INTEGER PRIMARY KEY,
    id_investigador         INTEGER NOT NULL,
    Nombre                  VARCHAR2(50) NOT NULL,
    Cantidad                INTEGER NOT NULL,
    FOREIGN KEY (id_investigador) REFERENCES Investigadores(id_investigador)
);


CREATE TABLE Biblioteca(
    id_Biblioteca       INTEGER PRIMARY KEY,
    id_usuario         INTEGER NOT NULL,
    CantidadMaterial    INTEGER NOT NULL,
    GestionPrestamo     INTEGER NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(id_usuario)
);

